Use new EventDatabaseProvider implementation
cafienne/getting-started pull request #25
Opened 2024-11-04 17:56 UTC by dannykruitbosch

The getting started local.conf was not yet updated to use the new EventDatabaseProvider implementation. This prevented the engine to start in the getting started.

2024-11-04 18:23 UTC, tpetter requested changes

2024-11-04 18:23 UTC, tpetter commented on src/conf/local.conf
>  akka-persistence-jdbc {
Kindly first rebase on main ;)

2024-11-04 20:17 UTC, dannykruitbosch commented on src/conf/local.conf
>  akka-persistence-jdbc {
Done

2024-11-04 20:26 UTC, dannykruitbosch commented
@tpetter seems my PR is not needed anymore since #24 contains the same fix. Close this one if you agree.

2024-11-05 07:02 UTC, tpetter commented
> @tpetter seems my PR is not needed anymore since #24 contains the same fix. Close this one if you agree.

Agreed

2024-11-08 08:38 UTC, closed without merging